{{-- <!DOCTYPE html>
<html>
<head>
    <title>Diagnosis Report</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f9fafb; /* same soft homepage bg */
            color: #1f2937; /* dark gray text like homepage */
            padding: 30px;
        }
        .container {
            max-width: 700px;
            margin: auto;
            background-color: #ffffff; /* white card background */
            padding: 30px;
            border-radius: 12px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.1); /* subtle shadow */
        }
        h1 {
            text-align: center;
            color: #2563eb; /* homepage primary color */
            margin-bottom: 20px;
        }
        .section {
            margin-bottom: 20px;
        }
        .section strong {
            display: block;
            font-size: 1.1em;
            margin-bottom: 5px;
            color: #111827;
        }
        ul {
            list-style-type: disc;
            padding-left: 20px;
        }
        .footer {
            text-align: center;
            font-size: 0.9em;
            color: #6b7280;
            margin-top: 30px;
        }
    </style>
</head>
<body>
    <h2>Health Diagnosis Report</h2>
    <div class="info">
        <p><strong>Name:</strong> {{ $name }}</p>
        <p><strong>Age:</strong> {{ $age }}</p>
        <p><strong>Gender:</strong> {{ $gender }}</p>
        <p><strong>Date:</strong> {{ date('d M Y', strtotime($date)) }}</p>
    </div>

    <div class="symptoms">
        <strong>Symptoms:</strong>
        <ul>
            @foreach($symptoms as $symptom)
                <li>{{ ucwords(str_replace('_', ' ', $symptom)) }}</li>
            @endforeach
        </ul>
    </div>

    <div class="diagnosis">
        <strong>Predicted Disease:</strong> {{ $diagnosis }}
    </div>
    
        <div class="footer">
    Generated by Health Issue Detector • 
    {{ \Carbon\Carbon::parse($created_at)->format('F j, Y, g:i a') }}
</div>

    </div>
</body>
</html> --}}
{{-- 
<!DOCTYPE html>
<html>
<head>
    <title>Diagnosis Report</title>
</head>
<body>
    <h1>Health Diagnosis Report</h1>
    <p><strong>Name:</strong> {{ $name }}</p>
    <p><strong>Age:</strong> {{ $age }}</p>
    <p><strong>Gender:</strong> {{ $gender }}</p>
    <p><strong>Diagnosis:</strong> {{ $diagnosis }}</p>
    <p><strong>Symptoms:</strong> {{ implode(', ', $symptoms) }}</p>
    <p><strong>Date:</strong> {{ $date }}</p>
</body>
</html> --}}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Health Diagnosis Report</title>
    <style>
        body {
            font-family: 'Poppins', 'Quicksand', sans-serif;
            background-color: #f4f7f6;
            color: #333;
            margin: 0;
            padding: 0;
        }

        .report-wrapper {
            max-width: 800px;
            margin: 40px auto;
            background-color: #ffffff;
            padding: 40px;
            border-radius: 10px;
            box-shadow: 0 8px 20px rgba(0,0,0,0.1);
            border-top: 8px solid #28a745;
        }

        .report-header {
            text-align: center;
            margin-bottom: 30px;
        }

        .report-header h1 {
            color: #28a745;
            font-size: 30px;
            margin-bottom: 5px;
        }

        .report-header p {
            font-size: 16px;
            color: #555;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            font-size: 16px;
        }

        table th, table td {
            text-align: left;
            padding: 12px 15px;
            border-bottom: 1px solid #e0e0e0;
        }

        table th {
            background-color: #e6f4ea;
            color: #28a745;
            font-weight: 600;
        }

        .symptoms {
            background-color: #e6f4ea;
            padding: 5px 10px;
            border-radius: 8px;
            display: inline-block;
        }

        .report-footer {
            margin-top: 40px;
            text-align: right;
            font-style: italic;
            color: #555;
        }

        @media print {
            body {
                background-color: #fff;
            }
            .report-wrapper {
                box-shadow: none;
                border-top: 6px solid #28a745;
                margin: 0;
                padding: 20px;
            }
        }
    </style>
</head>
<body>
    <div class="report-wrapper">
        <!-- Header -->
        <div class="report-header">
            <h1>Health Diagnosis Report</h1>
            <p>Comprehensive AI-based health analysis</p>
        </div>

        <!-- Report Table -->
        <table>
            <tr>
                <th>Name</th>
                <td>{{ $name }}</td>
            </tr>
            <tr>
                <th>Age</th>
                <td>{{ $age }}</td>
            </tr>
            <tr>
                <th>Gender</th>
                <td>{{ $gender }}</td>
            </tr>
            <tr>
                <th>Diagnosis</th>
                <td>{{ $diagnosis }}</td>
            </tr>
            <tr>
                <th>Symptoms</th>
                <td><span class="symptoms">{{ implode(', ', $symptoms) }}</span></td>
            </tr>
        </table>

        <!-- Footer -->
        <div class="report-footer">
            <p>Date: {{ $date }}</p>
        </div>
    </div>
</body>
</html>

